version: "3.7"
services:
  database:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "10000:5432"
    container_name: TortoiseORM-FastAPI_DB
